/**
 * POST /api/agent
 *
 * Spacze AI Agent — streaming orchestrator.
 *
 * Architecture:
 *   1. Receives a conversation history from the client.
 *   2. Passes it to the model with the full tool registry.
 *   3. The model reasons, calls tools, observes results, and loops until
 *      it has a final answer (maxSteps = 10 prevents infinite loops).
 *   4. Streams the response back using the Vercel AI SDK data stream protocol
 *      so the client can render text tokens and tool call events in real time.
 *
 * Provider fallback: OpenAI → Groq → Gemini (same order as other routes).
 */

import { streamText, stepCountIs, convertToModelMessages, createUIMessageStreamResponse } from 'ai';
import { createOpenAI } from '@ai-sdk/openai';
import { createGoogleGenerativeAI } from '@ai-sdk/google';
import { createGroq } from '@ai-sdk/groq';
import { NextRequest } from 'next/server';
import { agentTools } from '@/lib/agent-tools';
import { SPACZE_VOICE } from '@/lib/ai-persona';

// ── System prompt ─────────────────────────────────────────────────────────────

const SYSTEM_PROMPT = `${SPACZE_VOICE}

You are the Spacze AI Agent — an autonomous business operator for the Spacze Command Centre.

Your role is to help the Spacze team execute outreach, manage leads, run campaigns, and analyse performance. You have access to the following tools:

- getLeads: fetch and filter leads from the CRM
- analyzeLead: scrape and score a lead's website with AI
- generateCopy: generate personalised outreach copy for any platform
- sendEmail: send an outreach email to a lead
- sendWhatsApp: send a WhatsApp message to a lead
- updateLead: update a lead's CRM status or fields
- createCampaign: create a campaign and schedule a full outreach sequence
- getCampaignStats: get performance stats for campaigns
- processQueue: fire all scheduled messages that are due now

BEHAVIOUR RULES:
1. Always think step-by-step before acting. State your plan briefly before executing tools.
2. When asked to run outreach for a group of leads, fetch them first, then act on each one.
3. Before sending any message, generate the copy first and include it in your response so the user can see what will be sent.
4. Never send messages without first confirming the copy exists (either pre-generated or generated by you).
5. After completing a multi-step task, summarise what was done: how many leads contacted, which channels, any failures.
6. If a tool fails, explain why and suggest a fix — don't silently skip.
7. Keep responses concise. Use bullet points for lists of actions taken.
8. You are operating inside the Spacze admin — the user is the Spacze team, not a client.`;

// ── Provider list (ordered: OpenAI → Groq → Gemini) ──────────────────────────

function getModels() {
  const models = [];
  if (process.env.OPENAI_API_KEY) {
    const openai = createOpenAI({ apiKey: process.env.OPENAI_API_KEY });
    models.push({ name: 'openai', model: openai('gpt-4o-mini') });
  }
  if (process.env.GROQ_API_KEY) {
    const groq = createGroq({ apiKey: process.env.GROQ_API_KEY });
    models.push({ name: 'groq', model: groq('llama-3.3-70b-versatile') });
  }
  if (process.env.GEMINI_API_KEY) {
    const google = createGoogleGenerativeAI({ apiKey: process.env.GEMINI_API_KEY });
    models.push({ name: 'gemini', model: google('gemini-2.0-flash') });
  }
  return models;
}

// ── Route handler ─────────────────────────────────────────────────────────────

export async function POST(req: NextRequest) {
  const { messages } = await req.json();

  if (!Array.isArray(messages) || messages.length === 0) {
    return new Response(JSON.stringify({ error: 'messages array required' }), {
      status: 400,
      headers: { 'Content-Type': 'application/json' },
    });
  }

  const providers = getModels();
  if (providers.length === 0) {
    return new Response(
      JSON.stringify({ error: 'No AI provider configured. Set OPENAI_API_KEY, GROQ_API_KEY, or GEMINI_API_KEY.' }),
      { status: 500, headers: { 'Content-Type': 'application/json' } },
    );
  }

  const modelMessages = await convertToModelMessages(messages);
  let lastError: unknown;

  for (const { name, model } of providers) {
    try {
      const result = streamText({
        model,
        system: SYSTEM_PROMPT,
        messages: modelMessages,
        tools: agentTools,
        stopWhen: stepCountIs(10),
        temperature: 0.4,
        maxRetries: 0, // disable SDK retries so errors surface immediately
      });

      // Pull the first chunk from the UI message stream to force the provider
      // connection — auth errors (invalid key, quota exceeded) throw here.
      const uiStream = result.toUIMessageStream();
      const reader = uiStream.getReader();
      const first = await reader.read(); // throws if the provider rejects

      // Provider accepted — reconstruct the stream with the first chunk
      // prepended and return it as a proper SSE response.
      const replayed = new ReadableStream({
        async start(controller) {
          if (!first.done) controller.enqueue(first.value);
          try {
            while (true) {
              const { value, done } = await reader.read();
              if (done) break;
              controller.enqueue(value);
            }
          } catch (e) {
            controller.error(e);
          }
          controller.close();
        },
      });

      return createUIMessageStreamResponse({ stream: replayed });
    } catch (err) {
      console.warn(`[agent] ${name} failed, trying next provider:`, err instanceof Error ? err.message : err);
      lastError = err;
    }
  }

  const msg = lastError instanceof Error ? lastError.message : 'All AI providers failed';
  return new Response(JSON.stringify({ error: msg }), {
    status: 500,
    headers: { 'Content-Type': 'application/json' },
  });
}
